### ISSUE TITLE
是否注解方法为目前最好的解决方案?

### ISSUE THREAD

**Issue by shawnWiDang** [KeshawnVan/SpecificationBuilder#2]
在tk.mybatis开源的代码中,似乎存在更好的一个解决方案,可以参考一波改进一下.

**Comment by KeshawnVan** [comment]
看了下tk.mybatis类似于Spring Data JPA，这个我在orign项目里实现类似的功能。
这个项目是为了简化Spring Data JPA中动态查询比较繁琐的问题。
只是常规的查询，原生的Spring Data JPA就足够好用了。
